baseURL = 'https://joelmgallant.com'
languageCode = 'en-us'
title = '[joelmgallant]'
theme = 'awesome-identity'


## Profile Configurations
[params.profile]
  portrait = "/images/headshot.jpg"
  firstname = "Joel"
  lastname = "Gallant"
  title = """
    Technical Leadership | 
    Generalist Technologist
  """
  bio = """
    DevOps, Distributed Apps, AI,\n
    Media, Management [and more]
    """

## More things to click on
[params.actions]
  resume.name = "CV (PDF)"
  resume.url = "/resume-joelmgallant.pdf"

## Contacts Configurations
[params.contacts]
  email = "joelmgallant@gmail.com"
  github = "joelmgallant"
  facebook = "joelmgallant"
  instagram = "joelmgallant"
  linkedin = "joelmgallant"


## Footer Configurations
[params.footer]
  copyright = "© Joel Gallant, 2023"
  poweredBy = true
